spring:
  h2:
    console:
      enabled: true
      path:   /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    elasticsearch:
      cluster-name: poc-group-search
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  #  main:
  #    allow-bean-definition-overriding: true
org:
  springframework:
    data:
      elasticsearch:
        client:
          WIRE:
            level: trace

server:
  port: 9090



