spring:
  h2:
    console:
      enabled: true
      path:   /h2-console
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    elasticsearch:
      cluster-name: poc-group-search
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  #  main:
  #    allow-bean-definition-overriding: true
org:
  springframework:
    data:
      elasticsearch:
        client:
          WIRE:
            level: trace

server:
  port: 9090

logging:
  level:
    org:
      hibernate:
        SQL: debug
        #this will print the value passed in sql.
        #type:
          #descriptor:
            #sql: trace






